BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CompanyController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        var objCompanyList = _unitOfWork.Company.GetAll().ToList();
        return View(objCompanyList);
    }
    
    public IActionResult Upsert(int? id)
    {
        var company = new Company();
        if (id == null || id == 0)
        {
            //create
            return View(company);
        }
        else
        {
            //update
            company = _unitOfWork.Company.GetValueOrDefault(u => u.Id == id);
            return View(company);
        }
    }

    [HttpPost, ActionName("Upsert")]
    public IActionResult UpsertPost(Company company, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            if (company.Id == 0)
            {
                _unitOfWork.Company.Add(company);
            }
            else
            {
                _unitOfWork.Company.Update(company);
            }

            _unitOfWork.Save();
            TempData["success"] = "Product created successfully";
            return RedirectToAction("Index");
        }
        else
        {
            return View(company);
        }
    }
    
    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    {
        var objProductList = _unitOfWork.Company.GetAll().ToList();
        return Json(new { data = objProductList });
    }
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        Company? obj = _unitOfWork.Company.GetValueOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOfWork.Company.Delete(obj);

        _unitOfWork.Save();
        TempData["success"] = "Company deleted successfully";

        return RedirectToAction("Index");
    }
    #endregion
}

BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;

        }
        public IActionResult Index()
        {
            var objProductList = _unitOfWork.Product.GetAll(includeProperties:"Category").ToList();
            
            return View(objProductList);
        }

        public IActionResult Upsert(int? id)
        {
            ProductView productView = new ProductView()
            {
                CategoryList = _unitOfWork.Category
                    .GetAll().Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString()
                    }),
                Product = new Product()
            };
            if (id == null || id == 0)
            {
                //create
                return View(productView);

            }
            else
            {
                //update
                productView.Product = _unitOfWork.Product.GetValueOrDefault(u => u.Id == id);
                return View(productView);
            }

        }

        [HttpPost, ActionName("Upsert")]
        public IActionResult UpsertPost(ProductView productView, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");

                    if (!string.IsNullOrEmpty(productView.Product.ImageURL))
                    {
                        //delete old image
                        var oldImagePath =
                            Path.Combine(wwwRootPath, productView.Product.ImageURL.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productView.Product.ImageURL = @"\images\product\" + fileName;
                }

                if (productView.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productView.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(productView.Product);
                }

                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                productView.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(productView);
            }
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProductList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.GetValueOrDefault(u => u.Id == id);
            if (productToBeDeleted == null)
            {
                return Json(new {success = false, MessageProcessingHandler = "Error while deleting" });
            }

            if (productToBeDeleted.ImageURL != null)
            {
                var oldImagePath = 
                    Path.Combine(_webHostEnvironment.WebRootPath, 
                        productToBeDeleted.ImageURL.TrimStart('\\'));
            
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            _unitOfWork.Product.Delete(productToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message="Delete Successful" });

        }
        #endregion
    }

}

BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
@model List<Company>

<div class="card shadow border-0 my-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Company List</h2>
            </div>
        </div>
    </div>
   <div class="card-body p-4">
           <div class="row pb-3">
               <div class="col-6">
   
               </div>
               <div class="col-6 text-end">
                   <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                       <i class="bi bi-plus-lg"></i> Create New Company
                   </a>
               </div>
           </div>
           <table id="tblData" class="table table-bordered table-striped">
               <thead>
               <tr>
                   <th>
                       Name
                   </th>
                   <th>
                       Phone number
                   </th>
                   <th></th>
               </tr>
               </thead>
           </table>
       </div>
</div>

@section Scripts{
    <script src="~/js/company.js"></script>
}

BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 my-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> @(Model.Id != 0 ? "Update" : "Create") Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-10">
                    <div class="border p-3 mt-4">
                         <div class="form-floating py-2 col-12">
                                            <input asp-for="Name" class="form-control border-0 shadow"/>
                                            <label asp-for="Name" class="ms-2"></label>
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        <div class="form-floating py-2 col-12">
                                            <input asp-for="PhoneNumber" class="form-control border-0 shadow"/>
                                            <label asp-for="PhoneNumber" class="ms-2"></label>
                                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                        </div>
                                        <div class="form-floating py-2 col-12">
                                            <input asp-for="StreetAddress" class="form-control border-0 shadow"/>
                                            <label asp-for="StreetAddress" class="ms-2"></label>
                                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        
                                        </div>
                                        <div class="form-floating py-2 col-12">
                                            <input asp-for="City" class="form-control border-0 shadow"/>
                                            <label asp-for="City" class="ms-2"></label>
                                            <span asp-validation-for="City" class="text-danger"></span>
                        
                                        </div>
                                        <div class="form-floating py-2 col-12">
                                            <input asp-for="State" class="form-control border-0 shadow"/>
                                            <label asp-for="State" class="ms-2"></label>
                                            <span asp-validation-for="State" class="text-danger"></span>
                        
                                        </div>
                                        <div class="form-floating py-2 col-12">
                                            <input asp-for="PostalCode" class="form-control border-0 shadow"/>
                                            <label asp-for="PostalCode" class="ms-2"></label>
                                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        
                                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>

                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Product" asp-action="Index" class="btn btn-outline-primary border  form-control">
                                    Back To List
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>


@section Scripts{
    @{
        // <script>
        //     tinymce.init({
        //         selector: 'textarea',
        //         plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons lists table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
        //         toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap',
        //         tinycomments_mode: 'embedded',
        //         tinycomments_author: 'Author name',
        //         mergetags_list: [
        //             { value: 'First.Name', title: 'First Name' },
        //             { value: 'Email', title: 'Email' },
        //         ],
        //         ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant"))
        //     });
        // </script>
        <partial name="_ValidationScriptsPartial" />
    }
}